import fs from "fs";
import path from "path";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ScaleWrapper } from "@/components/scaleWrapper";
import { SceneProvider } from "@/contexts/SceneContext";
import { MasterProvider } from "@/contexts/MasterContext";
import { fetchScenes, fetchIdeaList } from "@/lib/sheets";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const scenes = await fetchScenes();
  const ideaList = await fetchIdeaList();
  const images = getImagePreloads();

  return (
    <html lang="en">
      <head>
        {images.map((src) => (
          <link key={src} rel="preload" as="image" href={src} />
        ))}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScaleWrapper>
          <MasterProvider scenes={scenes} ideaList={ideaList}>
            <SceneProvider scenes={scenes}>{children}</SceneProvider>
          </MasterProvider>
        </ScaleWrapper>
      </body>
    </html>
  );
}

function getImagePreloads() {
  const dir = path.join(process.cwd(), "public/images");
  const files = fs.readdirSync(dir);

  return files
    .filter((file) => /\.(png|jpg|jpeg|webp|avif)$/i.test(file))
    .map((file) => `/images/${file}`);
}
